name: Check Release Versions

on:
  schedule:
    # Runs 20 minutes past the hour
    - cron: '20 * * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Check release versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./.github/scripts/check_releases.py

      - name: Debug file existence
        run: |
          if [ -f ./release_versions.json ]; then
            echo "release_versions.json found";
            cat ./release_versions.json;
          else
            echo "Error: release_versions.json not created!";
            exit 1;
          fi

      - name: Verify release_versions.json exists
        run: |
          if [ ! -f ./release_versions.json ]; then
              echo "Error: release_versions.json not found!";
              exit 1;
          fi

      - name: Upload release versions JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-versions
          path: ./release_versions.json
          overwrite: true

      - name: Push release_versions.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "release_versions.json updated"
          git push || echo "Nothing to push"
